- name: Install Java 1.8
  yum: name=java-1.8.0-openjdk state=present update_cache=yes

- name: install apache24
  yum: name=httpd state=present update_cache=yes

- name: start httpd service
  service: name=httpd state=started enabled=yes

- name: Install tomcat8
  yum: name=tomcat state=latest update_cache=yes

- name: Enable Tomcat8
  service: name=tomcat state=started enabled=yes
